# Controller Button Mappings
BUTTON_A = 0
BUTTON_B = 1
BUTTON_X = 2
BUTTON_Y = 3
BUTTON_LB = 4
BUTTON_RB = 5
BUTTON_BACK = 6
BUTTON_START = 7
BUTTON_L3 = 8
BUTTON_R3 = 9

# Analog Controls
LEFT_ANALOG_X = 0
LEFT_ANALOG_Y = 1
RIGHT_ANALOG_X = 2
RIGHT_ANALOG_Y = 3
TRIGGER_L2 = 4
TRIGGER_R2 = 5

# Mouse Button Mappings
LEFT_CLICK = BUTTON_A
RIGHT_CLICK = BUTTON_B
MIDDLE_CLICK = BUTTON_X
SCROLL_SPEED_DOWN = BUTTON_LB
SCROLL_SPEED_UP = BUTTON_RB
MOUSE_SENSITIVITY_DOWN = TRIGGER_L2
MOUSE_SENSITIVITY_UP = TRIGGER_R2
PAUSE_BUTTON = BUTTON_START

# Control Axes
MOUSE_CONTROL = (LEFT_ANALOG_X, LEFT_ANALOG_Y)
SCROLL_CONTROL = (RIGHT_ANALOG_X, RIGHT_ANALOG_Y)

# Mouse Configuration
MOUSE_SPEED = 20.0
MOUSE_SENSITIVITY = 3.0
MIN_SENSITIVITY = 0.5
MAX_SENSITIVITY = 7.0
DEADZONE = 0.1
ACCELERATION = 1.2
SENSITIVITY_ADJUSTMENT_RATE = 1.05

# Scroll Configuration
SCROLL_SENSITIVITY = 3
SCROLL_SENSITIVITY_ADJUSTMENT_RATE = 1.5
MIN_SCROLL_SENSITIVITY = 0.5
MAX_SCROLL_SENSITIVITY = 7.0
MAX_SCROLL_VALUE = 100

# System Configuration
EVENT_CHECK_INTERVAL = 0.1
