# Xbox Controller Button Constants
BUTTON_A = 0
BUTTON_B = 1
BUTTON_X = 2
BUTTON_Y = 3
BUTTON_LB = 4
BUTTON_RB = 5
BUTTON_BACK = 6
BUTTON_START = 7
BUTTON_L3 = 8
BUTTON_R3 = 9

# Analog Sticks and Triggers
LEFT_ANALOG_X = 0     # Left stick X axis
LEFT_ANALOG_Y = 1     # Left stick Y axis
RIGHT_ANALOG_X = 2    # Right stick X axis
RIGHT_ANALOG_Y = 3    # Right stick Y axis
TRIGGER_L2 = 4        # Left trigger axis
TRIGGER_R2 = 5        # Right trigger axis

# Button Action Mappings
LEFT_CLICK = BUTTON_A
RIGHT_CLICK = BUTTON_B
MIDDLE_CLICK = BUTTON_X

EXIT_BUTTON = BUTTON_START

SCROLL_SPEED_DOWN = BUTTON_LB
SCROLL_SPEED_UP = BUTTON_RB

MOUSE_SENSITIVITY_DOWN = TRIGGER_L2
MOUSE_SENSITIVITY_UP = TRIGGER_R2

# Stick Action Mappings
MOUSE_CONTROL = (LEFT_ANALOG_X, LEFT_ANALOG_Y)      # Mouse movement
SCROLL_CONTROL = (RIGHT_ANALOG_X, RIGHT_ANALOG_Y)   # Scrolling

# Mouse Settings
MOUSE_SPEED = 20.0
MOUSE_SENSITIVITY = 3.0
MIN_SENSITIVITY = 0.5
MAX_SENSITIVITY = 7.0
DEADZONE = 0.1
ACCELERATION = 1.2
SENSITIVITY_ADJUSTMENT_RATE = 1.05

# Scroll sensitivity adjustment
SCROLL_SENSITIVITY = 3
SCROLL_SENSITIVITY_ADJUSTMENT_RATE = 1.5
MIN_SCROLL_SENSITIVITY = 0.5
MAX_SCROLL_SENSITIVITY = 7.0
